FROM node:18-alpine AS builder

WORKDIR /app

# Install necessary build tools
RUN apk add --no-cache libc6-compat openssl1.1-compat

COPY package*.json ./
COPY packages/db/package*.json ./packages/db/
COPY packages/db/prisma ./packages/db/prisma
COPY apps/http/package*.json ./apps/http/

RUN npm install
RUN cd packages/db && npx prisma generate

COPY . .
RUN npm run build --workspace=http

FROM node:18-alpine AS runner
WORKDIR /app

RUN apk add --no-cache openssl1.1-compat

COPY --from=builder /app/apps/http/dist ./dist
COPY --from=builder /app/apps/http/package.json .
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/db/prisma ./prisma

ENV NODE_ENV production
EXPOSE 3000

CMD ["node", "dist/index.js"]
